version: '2'

volumes:
  data:
    external:
      name: ci-pipeline-volume
  agent:
    external:
      name: ci-agent-volume
  repos:
    external:
      name: git-repo-volume

services:
  gitea-server:
    name: gitea-server
    image: kunde21/gitea-arm:v1.2.2
    ports: 
      - "3000:3000"
      - "1022:22"
    volumes:
      - repos:/data
    restart: always

  drone-server:
    name: gitea-server
    image: kunde21/drone-arm:v0.8.1
    ports:
      - "8000:8000"
    volumes:
      - data:/var/lib/drone/
    restart: always
    depends_on: [ gitea-server ]
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gitea-server:3000
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: kunde21/drone-arm:v0.8.1
    command: /drone-agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent:/var/lib/drone/
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}
