version: '2'

volumes:
  data:
    external:
      name: ci-pipeline-volume
  agent:
    external:
      name: ci-agent-volume

services:
  drone-server:
    image: kunde21/drone-arm:v0.7.0
    ports:
      - "8000:8000"
    volumes:
      - data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs-server:3000
      - DRONE_GOGS_SKIP_VERIFY=true
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: kunde21/drone-arm:v0.7.0
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent:/var/lib/drone/
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
